import { App } from "./App";
import "./globals.css";
import { Sidebar } from "@/components";

export const metadata = {
  title: "Interceping Route Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const loginSegments = useSelectedLayoutSegment("authModal");
  return (
    <html lang="en">
      <body id="__next">
        <Sidebar />
        <main className="lg:pl-72 py-4">
          <div className="px-4 sm:px-6 lg:px-8">
            <App>{children}</App>
          </div>
        </main>
      </body>
    </html>
  );
}
