import { cookies } from "next/headers";
import { App } from "./App";
import "./globals.css";
import { Sidebar } from "@/components";

export const metadata = {
  title: "Interceping Route Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  const nextCookies = cookies();
  const token = nextCookies.get("token");

  // const isLoggedIn = false;

  // const loginSegments = useSelectedLayoutSegment("authModal");
  return (
    <html lang="en">
      <body id="__next">
        <App>
          {children}
          {authModal}
        </App>
      </body>
    </html>
  );
}
